site_name: Kanade

site_url: https://alexrintt.github.io/kanade
site_author: Alex Rintt
site_description: "Android app to extract apks from installed apps."

repo_name: alexrintt/kanade
repo_url: https://github.com/alexrintt/kanade

nav:
  - Installation and usage: user-guide.md
  - Features: features.md
  - Build yourself: build-yourself.md
  - How it works: how-it-works.md
  - Donate: donate.md
  - Privacy: privacy-policy.md

theme:
  name: material
  custom_dir: material
  logo: assets/icons/mono_favicon.png
  palette:
    primary: black
  features:
    - header.autohide
  favicon: assets/icons/mono_favicon.png

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      watch:
        - material

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
