name: Validate fastlane actions

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  validate-fastlane:
    # required to run on Linux because this is a docker container action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
        with:
          fastlaneDir: ./modules/flutter_app/fastlane # optional
          # usePlayStoreLocales: true # optional
